### ISSUE TITLE
visualize the res image

### ISSUE THREAD

**Issue by jxLiang666** [xieKKKi/MotionBEV#2]
Hi, firstly thanks for your wonderful job.
And I wanna know whether you try to visualize the polar res image?
Cuz I wanna know why polar res image could be better as motion features ?
I have tried to visualize the polar res image like motionseg3d, however I failed, I couldn't find the var that I need or I don't know how to process it .
So if it is possible, could you provide me some guidance..
Thanks in advance!

**Comment by LeoZhiheng** [comment]
> Hi, firstly thanks for your wonderful job. And I wanna know whether you try to visualize the polar res image? Cuz I wanna know why polar res image could be better as motion features ? I have tried to visualize the polar res image like motionseg3d, however I failed, I couldn't find the var that I need or I don't know how to process it . So if it is possible, could you provide me some guidance.. Thanks in advance!

I think that MotionBEV gets promising performance since its data preprocessing has obtained a good initial result.
Meanwhile, BEV perspective may indeed be easier to capture motion than range view.

**Comment by jxLiang666** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jxLiang666** [comment]
> > Hi, firstly thanks for your wonderful job. And I wanna know whether you try to visualize the polar res image? Cuz I wanna know why polar res image could be better as motion features ? I have tried to visualize the polar res image like motionseg3d, however I failed, I couldn't find the var that I need or I don't know how to process it . So if it is possible, could you provide me some guidance.. Thanks in advance!
> 
> I think that MotionBEV gets promising performance since its data preprocessing has obtained a good initial result. Meanwhile, BEV perspective may indeed be easier to capture motion than range view.

Thanks for your reply. You are right, BEV in some conditions performs better than RV. Both of them have their own pros, so I try to visualize the polar image to find out the reason and finally I think that the motion information is in the 8 channels since the result of visual  image about single channel is not good.

**Comment by LeoZhiheng** [comment]
I'm curious if you're in the same research group as the author of MF-MOS. That's a great job.
Sincerely hope that we have the opportunity for in-depth communication. Thank you very much.
My Email: zhihengli@stumail.neu.edu.cn

**Comment by LeoZhiheng** [comment]
> > > Hi, firstly thanks for your wonderful job. And I wanna know whether you try to visualize the polar res image? Cuz I wanna know why polar res image could be better as motion features ? I have tried to visualize the polar res image like motionseg3d, however I failed, I couldn't find the var that I need or I don't know how to process it . So if it is possible, could you provide me some guidance.. Thanks in advance!
> > 
> > 
> > I think that MotionBEV gets promising performance since its data preprocessing has obtained a good initial result. Meanwhile, BEV perspective may indeed be easier to capture motion than range view.
> 
> Thanks for your reply. You are right, BEV in some conditions performs better than RV. Both of them have their own pros, so I try to visualize the polar image to find out the reason and finally I think that the motion information is in the 8 channels since the result of visual image about single channel is not good.

I'm curious if you're in the same research group as the author of MF-MOS. That's a great job.
Sincerely hope that we have the opportunity for in-depth communication. Thank you very much.
My Email: [zhihengli@stumail.neu.edu.cn](mailto:zhihengli@stumail.neu.edu.cn)
