### ISSUE TITLE
我是做动态环境下提高里程计精度的

### ISSUE THREAD

**Issue by CTT520** [xieKKKi/MotionBEV#3]
请问如何将该方法在ros环境下，.bin格式的点云数据如何转换为sensormsg::pointcloud2

**Comment by CTT520** [comment]
在ros环境下，以ros的消息格式进行通信，并进行神经网络的预测是可行的吗

**Comment by CTT520** [comment]
可以加个联系方式探讨嘛

**Comment by xieKKKi** [comment]
> 请问如何将该方法在ros环境下，.bin格式的点云数据如何转换为sensormsg::pointcloud2

可以参考[kitti2bag](https://github.com/tomas789/kitti2bag)，可以将bin格式点云转换成pointcloud2存储在bag文件中。

**Comment by xieKKKi** [comment]
> 在ros环境下，以ros的消息格式进行通信，并进行神经网络的预测是可行的吗

是可以的，只需要处理数据接口

**Comment by CTT520** [comment]
> > 在ros环境下，以ros的消息格式进行通信，并进行神经网络的预测是可行的吗
> 
> 是可以的，只需要处理数据接口

感谢大佬

**Comment by Anqfl** [comment]
> 请问如何将该方法在ros环境下，.bin格式的点云数据如何转换为sensormsg::pointcloud2
@CTT520 请问你尝试过吗？普通的游戏本配置可以跑通吗？
